name: Publish the Website

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build the website
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v3
        with:
          submodules: true
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          extended: true
      
      - name: Build the pages
        run: hugo --minify

      - name: Upload as a GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: public/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy the website
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy the GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.0
