name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build the pages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v3
      - name: Run a one-line script
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          extended: true
